// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jytsldbqgvntrqfjnkhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5dHNsZGJxZ3ZudHJxZmpua2h6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NjMwNTYsImV4cCI6MjA2ODMzOTA1Nn0.hxD4CAgsfVc1mKeYrjAzhJz_8MQoEnLXgxdUD8US_Yg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});